package _5.gxprogram.domain;

public enum programCategory {
    HEALTH, GX, SMALL_GROUP, SPORTS_CLIMBING, GOLF, MEASUREMENT, ONE_TIME_PASS,
    SQUASH, TENNIS, SATURDAY_SPORTS, TABLE_TENNIS, SQUASH_PRIVATE
}
